#!/bin/bash

# afrab-tee - part of agrab project
# Copyright (C) 2012 Basavanagowda Kanur
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301,
# USA.

#
# afrab-tee - Android FRAme Buffer TEE
#
# copy android's frame-buffer into a named pipe - @pipe
#

function init
{
    pipe=/tmp/android-display-trans-port-$device.pipe

    if [ -z "${ASDK_PATH}" ]; then
        ADB="adb"
    else
        ADB=${ASDK_PATH}/platform-tools/adb
    fi

    trap "rm -f $pipe" EXIT

    if [[ ! -p $pipe ]]; then
	mkfifo $pipe
    fi
}

function main
{
    while true; do
	${ADB} -s $device pull /dev/graphics/fb0 /dev/stdout \
	    1>>$pipe 2>/dev/null
    done
}

function usage
{
    echo "Usage: $0 [options]"
    echo
    echo "Options:"
    echo " -s, --serial=SERIAL-OF-ANDROID      serial identifier for emulator"
    echo " -A, --android-sdk=ANDROID-SDK-PATH  android sdk to use"
}

function parse_cmdline
{
    args=`getopt -u -o hs:A: --long help,serial:,android-sdk: -- "$@"`;

    if [ $? != 0 ]; then
        usage
	exit 2
    fi

    set -- $args

    for i; do
	case "$i" in
            -h|--help)
                usage;
                exit 0;;
	    -s|--serial)
		device=$2;
		shift;
		shift;;
            -A|--android-sdk)
                ASDK_PATH="$2";
                shift;
                shift;;
	    --)
		shift;
		break;;
	esac
    done
}

parse_cmdline "$@" && init && main
