#!/bin/bash

# afrab-enc - part of agrab project
# Copyright (C) 2012 Basavanagowda Kanur
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301,
# USA.

function init
{
    pipe=/tmp/android-display-trans-port-$device.pipe

    sleep 2;

    echo "$0: reading from device pipe - $pipe"

    if [[ ! -p $pipe ]]; then
	echo "display transporter not running"
	exit 1;
    fi

    rm -f ${output};
}

function main
{
    if [ -z "$LIVE" ]; then
	ffmpeg -r 30 -vcodec rawvideo -f rawvideo \
	    -pix_fmt rgb565 -s 480x800 -i $pipe \
	    -vcodec mpeg4 -re $output
    else
	output="rtmp://localhost/live/android-$device"

	echo "streaming live at - $output"

	ffmpeg -r 30 -vcodec rawvideo -f rawvideo \
	    -pix_fmt rgb565 -s 480x800 -i $pipe \
	    -vcodec mpeg4 -re $output
    fi
}

function usage
{
    echo "Usage: $0 [options]"
    echo
    echo "Options:"
    echo " -o, --output=OUTPUT-PATH"
    echo " -s, --serial=SERIAL-OF-ANDROID      serial identifier for emulator"
    echo " -L, --live"
}

function parse_cmdline
{
    if [ `uname` == "Darwin" ]; then
	args=`getopt ho:s:L $@`;
    elif [ `uname` == "Linux" ]; then
	args=`getopt -u -o ho:s:L --long help,output:,serial:,live -- "$@"`;
    else
	echo "You need a GNU/Linux or Mac OS X to run $0";
	exit 0;
    fi

    if [ $? != 0 ]; then
        usage
	exit 2
    fi

    set -- $args

    for i; do
	case "$i" in
            -h|--help)
                usage;
                exit 0;;
	    -s|--serial)
		device=$2;
		shift;
		shift;;
	    -o|--output)
		output=$2;
		shift;
		shift;;
	    -L|--live)
		LIVE="-L";
		echo "streaming live through rtmp";
		shift;;
	    --)
		shift;
		break;;
	esac
    done
}

parse_cmdline "$@" && init && main