#!/bin/bash

# agrab - entry point for the project Android frame-buffer GRABber
# Copyright (C) 2012 Basavanagowda Kanur
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301,
# USA.

function run_tee
{
    if [ -z "$device" ]; then
	echo "please specify a android device to attach to";
	exit;
    fi

    echo "starting android frame-buffer tee for $device";
    ./afrab-tee -s $device;
}

function run_encoder
{
    if [ -z "$output" ]; then
	output="agrab-$device.mp4";
	echo "no output file specified, using default - $output"
    fi

    ./afrab-enc -o $output -s $device $LIVE;
}

function main
{
    run_tee &
    run_encoder;
}

function parse_cmdline
{
    args=`getopt o:s:L $*`;

    if [ $? != 0 ]; then
	echo 'Usage: ...'
	exit 2
    fi

    set -- $args

    for i; do
	case "$i" in
	    -s)
		device=$2;
		shift;
		shift;;
	    -o)
		output=$2;
		shift;
		shift;;
	    -L)
		LIVE="-L";
		shift;;
	    --)
		shift;
		break;;
	esac
    done
}

parse_cmdline "$@" && main;